### ISSUE TITLE
能否支持2020版本的Air 14?

### ISSUE THREAD

**Issue by xqq1994** [lietxia/XiaoXinAir14IML_2019_hackintosh#1]
配置信息：
	
电脑型号	联想 81YJ 笔记本电脑  (扫描时间：2020年03月02日)
操作系统	Windows 10 64位 ( DirectX 12 )
	
处理器	英特尔 Core i5-1035G1 @ 1.00GHz 四核
主板	联想 LNVNB161216 ( I/O - 3482 for Intel 495 Series 芯片组 Family On-Package Platform Controller Hub )
内存	16 GB ( 三星 )
主硬盘	三星 MZVLB512HBJQ-000L2 ( 512 GB / 固态硬盘 )
显卡	Nvidia GeForce MX350 ( 2 GB )
显示器	奇美 CMN1408 ( 14 英寸  )
声卡	英特尔 英特尔智音技术音频控制器
网卡	英特尔 Wi-Fi 6 AX201 160MHz

**Comment by xqq1994** [comment]
听说PM981a不支持黑苹果，能否提供替代方案，随便放个京东链接地址？

**Comment by lietxia** [comment]
pm981a 有人发成果了，可能不用换 https://github.com/phenixcxz/xiaoXinPro-i5-PM981 处理器跟这个差别也很大的，虽然同是10代，但这是10nm的，需要自己测试，触摸板会很难驱动，显卡倒是统一被屏蔽。Wi-Fi肯定要换，可惜160mhz网卡了。

**Comment by ShangJixin** [comment]
@lietxia 那用这个仓库的方案 配合上面的那个方案 怎么上pm981a啊 谢谢qwq

**Comment by lietxia** [comment]
> @lietxia 那用这个仓库的方案 配合上面的那个方案 怎么上pm981a啊 谢谢qwq

已经有人花钱找装黑苹果的人测试了，10代10纳米和14纳米款不通用，手上没机型我也不保证可靠性，可以自行测试。

PM981A目前在mac下会有很多问题，暂时不推荐，上方PM981A发成果的人直接删源码了。

我本人直接加装512GBSSD，专门放mac，PM981A当从盘。

当然如果你有很强的动手能力，愿意花时间开荒+钻研。可以加项目首页的QQ群，我可以给一些建议和帮助

**Comment by takfate** [comment]
2020版可以直接适用？还有2020版的hdmi是什么版本啊

**Comment by lietxia** [comment]
有个难点是核显是否能驱动，这款能成功很大原因是 0代14纳米的CPU核显跟前几代一模一样。没有核显驱动的话图形会很卡，无法日常使用。10代10纳米的i7的1065G7，好像CPU在macOS10.15.3的支持列表里。有希望驱动核显。i5那个因为型号是1035G1，G1结尾核显是单独的型号，和别的都不同，比较难成功一些。

**Comment by takfate** [comment]
> 有个难点是核显是否能驱动，这款能成功很大原因是 0代14纳米的CPU核显跟前几代一模一样。没有核显驱动的话图形会很卡，无法日常使用。10代10纳米的i7的1065G7，好像CPU在macOS10.15.3的支持列表里。有希望驱动核显。i5那个因为型号是1035G1，G1结尾核显是单独的型号，和别的都不同，比较难成功一些。

G7有人成功过了嘛

**Comment by lietxia** [comment]
> > 有个难点是核显是否能驱动，这款能成功很大原因是 0代14纳米的CPU核显跟前几代一模一样。没有核显驱动的话图形会很卡，无法日常使用。10代10纳米的i7的1065G7，好像CPU在macOS10.15.3的支持列表里。有希望驱动核显。i5那个因为型号是1035G1，G1结尾核显是单独的型号，和别的都不同，比较难成功一些。
> 
> G7有人成功过了嘛

现在还没有成功案例，还需要有人开荒

**Comment by takfate** [comment]
> > > 有个难点是核显是否能驱动，这款能成功很大原因是 0代14纳米的CPU核显跟前几代一模一样。没有核显驱动的话图形会很卡，无法日常使用。10代10纳米的i7的1065G7，好像CPU在macOS10.15.3的支持列表里。有希望驱动核显。i5那个因为型号是1035G1，G1结尾核显是单独的型号，和别的都不同，比较难成功一些。
> > 
> > 
> > G7有人成功过了嘛
> 
> 现在还没有成功案例，还需要有人开荒

感觉没啥必要- -，感觉10210u跟8565u半斤八两啊。。

**Comment by junkaiman** [comment]
> 可以加项目首页的QQ群，我可以给一些建议和帮助

我手上这台新机器是Air2020, i7-1065G7，独显MX350

**Comment by marianopela** [comment]
> > 可以加项目首页的QQ群，我可以给一些建议和帮助
> 
> 我手上这台新机器是Air2020, i7-1065G7，独显MX350

Can you please let me know if you make any progress in booting the installer?
My friend is stuck here with the same device 
![A111137B-2491-48CF-9B13-F1E5278C6BA9](https://user-images.githubusercontent.com/42821024/79199737-b3046e80-7e35-11ea-81bc-05c49d2293ca.jpeg)

**Comment by lietxia** [comment]
10纳米的i7 1035G7版，有成功案例了。AIR14-2020 i7的可以去帖子跟作者讨论 

http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1852340&extra=&highlight=ice%2Blake&page=1

**Comment by lietxia** [comment]
小新air14(i5-1035G1) http://bbs.pcbeta.com/viewthread-1873103-1-1.html

[2020款小新air14_1035g1_EFI-OC0.6.2.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/5853401/2020.air14_1035g1_EFI-OC0.6.2.zip)

----

小新air14(i7-1065G7) http://bbs.pcbeta.com/viewthread-1878378-1-1.html
[XiaoXin Air14-2020-Intel-I7 1065G7.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/5853570/XiaoXin.Air14-2020-Intel-I7.1065G7.zip)
