### ISSUE TITLE
HDMI无法输出

### ISSUE THREAD

**Issue by lunasaw** [lietxia/XiaoXinAir14IML_2019_hackintosh#10]
想请教一下HDMI如何输出

**Comment by lietxia** [comment]
https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html
方法在这里，没有难点。但是需要不断尝试`总线ID`,`管道pip`等，不断修改+不断重启+尝试，直到试出机器的HDMI通道为止

**Comment by lunasaw** [comment]
感谢你的方法 已经成功 [ https://github.com/czy1024/XiaoXin-Air15-IKBR-2018-EFI/tree/master/BigSur]( https://github.com/czy1024/XiaoXin-Air15-IKBR-2018-EFI/tree/master/BigSur)
