### ISSUE TITLE
Latest release reported as OpenCore 0.6.4 

### ISSUE THREAD

**Issue by Hasodikis** [lietxia/XiaoXinAir14IML_2019_hackintosh#12]
Hi Lietxia many many thanks for your work!!!!!
Your latest release is based on OpenCore 0.6.5. according to the release info. 

However Hackintool and OpenCore Configurator report the config as based on OpenCore 0.6.4 .....

Could you look at it, so that we can avoid any future problems .?

**Comment by lietxia** [comment]
![image](https://user-images.githubusercontent.com/7046884/103965847-95342200-5199-11eb-88fe-c52a7bb545c1.png)

Open OpenCoreConfigurator `Preferences` and select `OC0.6.5Dev Version`.  
You'll be able to configure it

**Comment by Hasodikis** [comment]
Thanks for the reply.... 
I personally don't use OpenCore Configurator or Hackintool to edit my config.plist. 
I just point the matter because other people may face problems....

**Comment by lietxia** [comment]
ok, It is indeed necessary to remind.
Have you tried yogaSMC, which can adjust CPU performance mode.
https://github.com/zhen-zen/YogaSMC
![image](https://user-images.githubusercontent.com/7046884/103984169-97aa7200-51c1-11eb-8fcd-0028f4e2b5ee.png)

**Comment by Hasodikis** [comment]
Ok... 

I have tried YogaSMC on my ideapad for a few days.... its a very nice app. 
However my laptop is tuned to the lowest possible power consumption already. I am a lawyer and I only use safari, pages and preview (for the 99 % of time). So for me battery time and not performance is the most important thing.  

As soon as I get my new battery I will start using it to save its capacity .. Right now I am at 77% wear (on average because for some strange reason it fluctuates up and down).

I am bidding on a Thinkpad t460s right now ... and I will probably get it .... I will install MacOs on it and use also YogaSMC on it. ...
