### ISSUE TITLE
防止黑苹果间歇性断网-解决方案

### ISSUE THREAD

**Issue by Unstoppablesss** [lietxia/XiaoXinAir14IML_2019_hackintosh#17]
1. 系统偏好设置/电池/电源适配器/如果可能，使硬盘进入睡眠（修改为off）
如果硬盘进入休眠，保持wifi运转的EFI文件将停止工作
2.  只启用itlwm.kext, 采用外部软件heliport 加载Wi-Fi

**Comment by lietxia** [comment]
知道了，感谢

**Comment by CelestialSayuki** [comment]
It seems that all running kernel extensions are injected in RAM, not just read from your disk constantly.
