### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by marianopela** [lietxia/XiaoXinAir14IML_2019_hackintosh#2]
Hey, nice work!

Have you tried running trackpad in interrupts mode?
I've tried for several months with no luck (pin should be 0x0108)

**Comment by lietxia** [comment]
I tried for a few months, but the touchpad only works in polling mode

**Comment by marianopela** [comment]
Also, something strange is happening

Since the moment when VoodoI2C started relying on VoodooInput trackpad sometimes does not work after sleep/wake

Also tried on latest 2.4 VoodooI2C
Are you experiencing this too?

**Comment by lietxia** [comment]
No problem with sleep and wake. You can try this kexts. 
[trackpad.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4456552/trackpad.zip)

**Comment by marianopela** [comment]
Unfortunately they produce many error logs during boot, but I think I kind of solved by removing a presumed conflict with VoodooPS2 (both VoodooI2C and VoodooPS2 implement VoodooInput as an internal Plugin. I removed the one inside of VoodooPS2)

I'll be back after more testing. Thanks for now

**Comment by marianopela** [comment]
Ok, no more problems on Clover

I'm also moving my first steps on OC, and I'm experiencing two problems 

1. I can't boot with VirtualSMC 1.1.2. Can you please try updating your OpenCore.efi, BOOTx64.efi and Drivers and see if you face this too. Or, did you have that problem in the past? I opened an issue on Acidanthera/bugtracker but I'm still waiting for an answer

2. What is the correlation between XOSI and the patch for brightness keys? I noticed some strange behaviours yesterday. I can't get trackpad to work on OC in any way (I tried your SSDTs and kexts)

**Comment by lietxia** [comment]
I can boot with VirtualSMC 1.1.2 and openCore0.5.8(OpenCore.efi  BOOTx64.efi), no problem.

but i cannot boot any version of OpenCore with BIOS 1.0.2(BIOS Version: CKCN12WW) when I enable `Inter hyper-threading`

I see your model(Ideapad-S540-14IML) and I use the same BIOS file.

Ideapad-S540-14IML BIOS: CKCN12WW.exe
https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/ideapad-s-series-netbooks/s540-14iml/downloads/driver-list/component?name=BIOS%2FUEFI

XiaoXinAir14IML (BIOS Version: CKCN12WW,EC Version: CKEC12WW)
https://newsupport.lenovo.com.cn/driveList.html?fromsource=driveList&selname=%E5%B0%8F%E6%96%B0%20Air-14%202019%20(Intel%E5%B9%B3%E5%8F%B0%EF%BC%9AIML%E7%89%88)

maybe 2 ways can help you: 
1. flash BIOS to version 1.0.1(CKCN11WW) https://newsupport.lenovo.com.cn/driveDownloads_detail.html?driveId=67169 or direct download http://newdriverdl.lenovo.com.cn/newlenovo/alldriversupload/60449/BIOS-CKCN11WW.exe

2. disable `Inter hyper-threading` in BIOS version1.0.2(CKCN12WW)

----
In my model if use `SSDT-XOSI.aml`,trackpad is work and brightness keys(F11 F12) not work. need `SSDT-BKEY.aml` and edit `config.plist` add rename patches to fix it. you can see https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/releases/tag/2020.04.05

I watched your DSDT.aml . Same as me using `TPAD` in `_SB.PCI0.I2C0`,
I also don't know why the trackpad cannot work when you using `SSDT-XOSI.aml`.
maybe you can try run this code in terminal
```
sudo mount -uw /
killall Finder
sudo kextcache -i /
```

**Comment by marianopela** [comment]
Thanks for the support. I don't know how, but I booted with updated VirtualSMC!
I'm on latest Bios and HyperThreading is enabled.

Here is my current OC EFI. You can try it and see if you boot with it on latest Bios
[EFI.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4464687/EFI.zip)

Now I'm gonna study trackpad situation some more

**Comment by marianopela** [comment]
[EFI.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4464738/EFI.zip)
Ok it's working now. I needed both TPAD and XOSI patches

Btw, here https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/releases/tag/2020.04.05 you mistyped, because the SSDT you provided is called SSDT-XOSI.aml
![Screenshot 2020-04-11 at 16 16 21](https://user-images.githubusercontent.com/42821024/79046210-c9c97c00-7c0f-11ea-856d-0cf6fa5f74aa.png)

**Comment by lietxia** [comment]
good job

**Comment by lietxia** [comment]
Hello, My friend helped me make a new trackpad patch(mode:polling),You can try it.

1. replace `AIR14-TPAD.aml`
2. delete `SSDT-XOSI.aml` and `SSDT-BKEY.aml`
3. disable `change _OSI to XOSI` `_Q12 to XQ12` `_Q11 to XQ11` in `config.plist`

[AIR14-TPAD.aml.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4466104/AIR14-TPAD.aml.zip)

**Comment by marianopela** [comment]
Hey, thanks! I'll try that as soon as I can. I have a question though. Why do we need to replace the entire trackpad scope to make it work?

**Comment by lietxia** [comment]
> Hey, thanks! I'll try that as soon as I can. I have a question though. Why do we need to replace the entire trackpad scope to make it work?

I do not know

**Comment by marianopela** [comment]
Hey, I did some changes to VoodooI2C. Could you give them a try and tell me if you notice any changes?
[Archive.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4472217/Archive.zip)

**Comment by lietxia** [comment]
I tested it, but found no changes

**Comment by marianopela** [comment]
> I tested it, but found no changes

It's partially good, because at least I didn't break anything. I submitted a PR so people would look and review the code, and maybe something good will come out

I also wanted to ask you about sleep, because I tried leaving my laptop on with closed lid for the past 2 nights, but every morning I found out it had been "restarted due to an error"

I also analysed logs and found this
![](https://files.gitter.im/marianopela/T1BO/Screenshot-2020-04-14-at-17.35.52.png)

Don't you think we would need something like this?
[SSDT-RTC_Y-AWAC_N.aml.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4476905/SSDT-RTC_Y-AWAC_N.aml.zip)

I'm gonna test it tonight but wanted to ask your opinion

**Comment by lietxia** [comment]
Hey! My computer was broken by me ,And the repair took several weeks. I used your patch(SSDT-RTC_Y-AWAC_N.aml). But nothing seems to change

**Comment by marianopela** [comment]
Hi, I hope everything is ok now

> I used your patch(SSDT-RTC_Y-AWAC_N.aml). But nothing seems to change

That's strange. I need it in order for sleep to work properly

**Comment by marianopela** [comment]
Hey, is your USB C working?

**Comment by lietxia** [comment]
> Hey, is your USB C working?

 no problem, is working.

**Comment by marianopela** [comment]
Hey! How are you?

Are you aware of this project? https://github.com/zhen-zen/YogaSMC
I've been testing it to help develop the Ideapad features and solve errors. If you're interested and want to join the conversation there is an issue open on the repo

**Comment by lietxia** [comment]
> Hey! How are you?
> 
> Are you aware of this project? https://github.com/zhen-zen/YogaSMC
> I've been testing it to help develop the Ideapad features and solve errors. If you're interested and want to join the conversation there is an issue open on the repo

I'm happy to join the conversation. But I've been a little busy at work lately and will be available in 2 weeks.

**Comment by CelestialSayuki** [comment]
Closed because YogaSMC hasn’t been updated for almost six months. And it didn’t perform well in this model.
