### ISSUE TITLE
能只在MacOS禁言独显和PM981A吗？

### ISSUE THREAD

**Issue by Face-Smile** [lietxia/XiaoXinAir14IML_2019_hackintosh#21]
装了双系统，一个盘一个系统，不想在BIOS中切换显卡;
OC中加了 SSDT-DNVMe.aml, 屏蔽不了PM981a

**Comment by CelestialSayuki** [comment]
你进群里问一下吧，群里的小葵好像会这个。

**Comment by CelestialSayuki** [comment]
@sun19970908 你帮他屏蔽一下吧😁

**Comment by Face-Smile** [comment]
不用了，这几天已经折腾好了，
屏蔽pm981a我只加了文件，没在config. plist配置😂所以之前没用。
显卡之前是禁用好了的， 当时电脑发热严重，我以为是显卡没禁言成功， 最后发现是我那个垃圾USB以太网驱动不适配导致的😂
