### ISSUE TITLE
Monterey 键盘失灵替代解决方案

### ISSUE THREAD

**Issue by Unstoppablesss** [lietxia/XiaoXinAir14IML_2019_hackintosh#22]
# 在Monterey 12.1版本开机键盘失灵之后，可以插入一个usb接口的键盘，可以正常输入密码卡机。

现象：
Monterey 关机之后键盘会失灵，电脑在开机时的opencore界面以及在BIOS界面均有发生笔记本键盘失灵的现象，之前big sur 有时候也会这样。

键盘会失灵原因假设：
很可能是键盘仿冒id在改写笔记本自带键盘规则之后，在关机之前没有改回来，导致整台电脑的键盘失灵，电脑在开机时的opencore界面以及在BIOS界面均有发生笔记本键盘失灵的现象。然而在系统键盘失灵之后，USB键盘却没有被影响，这说明键盘功能完好，只是系统键盘那一块有点问题，这都可以证明这一点。

解决根本问题：
可能需要在关机之前将本系统的键盘仿冒修改回正常状态（可能之前的bigsur的版本里面的文件有8）

**Comment by lietxia** [comment]
vit有说过原因，是联想的固件有错误，靠opencore没法解决

原帖https://github.com/acidanthera/bugtracker/issues/1838

**Comment by Unstoppablesss** [comment]
嗯嗯

**Comment by Unstoppablesss** [comment]
感谢楼主，我看了一圈，感觉还是跳过密码自动登录吧，键盘挂了之后这样可能还方便些

**Comment by lietxia** [comment]
![bios](https://user-images.githubusercontent.com/7046884/159151799-dba7d112-2e96-448f-8721-22446f6fd923.jpg)
**bios里可能键盘会失灵**，先进一次别的系统  
开机按`F2`进入bios，然后在【boot】下设置：
1.  boot mode = leguacy support
2.  boot priority = Leguacy First 
缺点：开机会变慢

**Comment by CelestialSayuki** [comment]
Works fine after change boot mode to legacy support

**Comment by CelestialSayuki** [comment]
Fixed in later efi versions.
