### ISSUE TITLE
没有HDMI输出

### ISSUE THREAD

**Issue by boss521** [lietxia/XiaoXinAir14IML_2019_hackintosh#25]

**Comment by CelestialSayuki** [comment]
Did you modify DVMT?

**Comment by boss521** [comment]
nope , I will try it, thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lietxia/XiaoXinAir14IML_2019_hackintosh"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月25日(星期天) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lietxia/XiaoXinAir14IML_2019_hackintosh] 没有HDMI输出 (Issue #25)





 
Did you modify DVMT?

**Comment by Evanchaii** [comment]
This problem has been discussed a lot in qq group. However, there is no perfect solution so far. Many ways have been tried, including Xiaobin's blog：https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html#more.
Some friends got ideas from it, they found that board-id may cause this trouble. Using tool 'OC Auxiliary Tools', select 'NVRAM', second UUID, finding Key 'boot args', add "agdpmod=vit9696" at the end of this line(Value).
It is hard to explain in words without picture, so you'd better join us for further discussion, QQ group:1032311345.

**Comment by lietxia** [comment]
* 2022-09-27 12:00
    * Update Opencore to 0.8.4
    * Update Kexts
    * Add boot-args `agdpmod=vit9696` to solve hdmi output problem
    * Update beta PS2 keyboard kext, add boot-args `kbd_fixdisable=1` to solve macos12+ keyboard malfunction

----
* 2022-09-27 12:00
    * Opencore 更新到 0.8.4 
    * 更新驱动
    * 添加启动参数 `agdpmod=vit9696` 解决hdmi输出
    * 更新测试版PS2键盘驱动，添加启动参数 `kbd_fixdisable=1` 解决macos12以上键盘失灵

**Comment by CelestialSayuki** [comment]
Fixed in the latest efi
