### ISSUE TITLE
Debug BIOS sequence not working

### ISSUE THREAD

**Issue by 1alessandro1** [lietxia/XiaoXinAir14IML_2019_hackintosh#3]
Hi @daliansky, I own a Lenovo S740-14IIL, can you please explain how you got that sequence? I am not able to boot into the DEBUG bios mode, please help. 

Thank you

**Comment by lietxia** [comment]
1. shuntdown
2. boot and press F2 to enter BIOS
3. shuntdown
4. press 
F1 → 1 → Q → A → Z
F2 → 2 → W → S → X
F3 → 3 → E → D → C
F4 → 4 → R → F → V
F5 → 5 → T → G → B
F6 → 6 → Y → H → N
5. boot and press F2 to enter debug BIOS mode
6. If fails, try again

**Comment by marianopela** [comment]
We already tried several times on @1alessandro1 's device, without any luck. I can enter that mode on mine almost without any effort, so I think his device might need a different procedure. His model is the 14 inches with i7 1065G7, as I know China calls them with different names from with respect to Europe.

Anyway, thanks to Google Translate I understand you talked about a different method. Could it be a solution in case we don't find a way into Hidden Bios?
![Screenshot 2020-04-10 at 10 45 03](https://user-images.githubusercontent.com/42821024/78977388-58f36880-7b18-11ea-8a09-30bcba6eb925.png)

**Comment by lietxia** [comment]
No. It cannot into Hidden Bios.  Only modify DVMT and unlock CFG LOCK. Look at this: https://www.tonymacx86.com/threads/guide-broadwell-hd5500-setting-dvmt-in-insydeh20-bios-laptops.165104/

**Comment by 1alessandro1** [comment]
It says cannot modify variable from efi when I use setup_var and setup_var_3

**Comment by lietxia** [comment]
The method is to find the `offset`, and then use `Insyde H2OUV` to modify the BIOS settings

I'm sorry, my English is **NOT** very good. If you can read Chinese with a translator, you can read here.

https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/wiki/DVMT

If you can't read the article, I will find someone to translate it into English in a few days 

Maybe this forum can help you -> https://www.win-raid.com/t5005f16-Unlocking-advanced-options-in-Insyde-H-O-BIOS-for-Clevo-NH-RCQ-Hyperbook.html

**Comment by 1alessandro1** [comment]
Yes! I've managed to unlock the CFG-Lock and adjusted the DVMT settings thanks to your advices.

Just a little question, did some of you manage to boot an IceLake laptop, (in particular a [Lenovo IceLake Laptop?](https://www.insanelymac.com/forum/topic/343640-lenovo-yoga-s740-14iil/)) which forum are you consulting for daily troubleshooting?

Could it be this one? http://bbs.pcbeta.com/viewthread-1815623-1-1.html

anyway let me know if it's possible to get in contact with them, even if they are chinese geeks we could try to discuss though a translator (don't worry about the quality of your English, it's perfectly fine).

Thanks again, 

Ale

**Comment by lietxia** [comment]
Someone has succeeded IceLake laptop(i7-1065G7 and i5-1035G4), But the graphics card not working.

http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1852340

[Hasee-X57S1(i7-1065G7).zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4578090/Hasee-X57S1.i7-1065G7.zip)

[SurfacePro7(i5-1035G4).zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4578094/SurfacePro7.i5-1035G4.zip)

**Comment by wyq977** [comment]
@lietxia does the method for entering hidden BIOS also work xiaoxin pro 2020 i5 model? 

Also, how does one enter F2 F3... when power off? just F2 or Fn + F2 since the function keys are enable.

谢谢你啦 想问下小新pro13 2020 i5 可以进入吗？按键的时候要Fn+F2一起按还是只按下F2，因为默认是开启了功能键的

十分感谢 🙇‍♂️

**Comment by lietxia** [comment]
> @lietxia does the method for entering hidden BIOS also work xiaoxin pro 2020 i5 model?
> 
> Also, how does one enter F2 F3... when power off? just F2 or Fn + F2 since the function keys are enable.
> 
> 谢谢你啦 想问下小新pro13 2020 i5 可以进入吗？按键的时候要Fn+F2一起按还是只按下F2，因为默认是开启了功能键的
> 
> 十分感谢 🙇‍♂️

小新pro刷测试版bios就能直接解锁CFG lock和DVMT。

见 https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/DVMT%E8%A1%A5%E4%B8%81#%E6%B5%8B%E8%AF%95%E7%89%88bios

**Comment by wyq977** [comment]
谢谢🙏 已经刷了！

**Comment by CelestialSayuki** [comment]
Solved?
