### ISSUE TITLE
Integrated display goes black after apple boot logo

### ISSUE THREAD

**Issue by mandresve** [lietxia/XiaoXinAir14IML_2019_hackintosh#32]
Hi. I'm facing a new challenge with our hackintosh. After update to Ventura 13.4, the integrated display goes black after apple boot logo. The system is booting successfully, because external HDMI screen is working properly. The way I found to sort it out is to sleep the machine and resume it again, after that the screen goes on normally. Any solution hint? I'm using the iGPU because my machine doesn't have the dedicated GPU.

**Comment by mandresve** [comment]
Update: If I boot in verbose mode with -v flag, the integrated screen goes on normally!

**Comment by CelestialSayuki** [comment]
No solution, Apple modified the way to control backlight, the old igfxblr is no longer supporting the new system, we can wait for weg to update.

**Comment by mandresve** [comment]
Update: If I boot in verbose mode with -v flag, the integrated screen goes on normally most of the time. Indeed it's related to the backlight control. A temporary workaround is to set verbose mode on. Please keep us updated on this.



> No solution, Apple modified the way to control backlight, the old igfxblr is no longer supporting the new system, we can wait for weg to update.

I'll check further on this.

**Comment by mandresve** [comment]
Ventura 13.5 beta 1 doesn't seem affected by the bug and the patches work quite well as expected. I suggest to skip 13.4 and wait to 13.5, or update to 13.5 b1 asap.
