### ISSUE TITLE
VoltageShift + updated bios + Ventura (Solution)

### ISSUE THREAD

**Issue by Hasodikis** [lietxia/XiaoXinAir14IML_2019_hackintosh#33]
If you have updated the bios and want to use VoltageShift, you must enter the advanced bios menu and enable overclocking (its somewhere there, in the CPU/Power menu). 
If you dont that first, VoltageShift will not be able to offset the voltage. It took me many hours to find that out.

Its not an issue with your set up. I just write it as an advice all.

**Comment by CelestialSayuki** [comment]
I’ll update the readme in my spare time, thanks for your advice!

**Comment by CelestialSayuki** [comment]
Completed.
