### ISSUE TITLE
重置NVRAM后，卡在OpenCore初始化阶段

### ISSUE THREAD

**Issue by Z-fly** [lietxia/XiaoXinAir14IML_2019_hackintosh#34]
![d48bc78722c3af11aad5c9c06cb4d492](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/assets/10470892/7768a5e1-6386-470c-a24c-9f002c9a6ddf)

**Comment by CelestialSayuki** [comment]
Can you describe some more details such as which version are you using ?

**Comment by Z-fly** [comment]
使用的是2023-11-29-opencore-XiaoXinAir14IML2019.7z
按空格键，弹出Reset NVRAM，选到这项，然后重启后就卡在上图的界面了。

我已经解决了，用Clover再次重置NVRAM后，进入OpenCore就正常了
