### ISSUE TITLE
GPU睿频异常高达7.0Ghz

### ISSUE THREAD

**Issue by Jameslo1987** [lietxia/XiaoXinAir14IML_2019_hackintosh#37]
GPU负载时，频率异常高有时候瞬间达到7Ghz，istat能识别到7583Mhz，基本频率应该在1.2Ghz左右，只要看视频编解码，cpu就会降频至500-800Mhz，整个系统会异常卡顿。
![Screenshot 2024-08-08 at 02 42 51](https://github.com/user-attachments/assets/f9c532fc-9c5b-46d9-85f0-1cd44d93aabe)
![Screenshot 2024-08-08 at 03 13 58](https://github.com/user-attachments/assets/6773b689-9c1a-4895-b355-00ce50de155f)

看过很多issue有说温度太高降频什么的，要贴硅胶加强散热之类。也有说CPUFriend重新定制频率，试过都无效。
win下测试过，GPU满载睿频很正常，从来不会超过1.2Ghz，加强散热这种做法根本不是正确思路。

其实就是需要在MAC下正常睿频就可以解决这个问题，但是换了很多个 ig-platform-id 和 device-id 没有一个能正常睿频。

这个情况发生在10710u / 10510u / 10210u 的GPU上，我看到有些提问相关涉及睿频的，他们Intel power gadget GFX AVG的睿频全部都会超过基准频率。

挖了一些资料发现10710u / 10510u / 10210u 这个系列的GPU是，Comet Lake GPU，用Hackintosh查了一下没有Comet Lake的补丁。
虽然用coffee lake的补丁也能正常驱动，但是不清楚是不是这个原因导致GPU睿频异常。
![Screenshot 2024-08-08 at 03 00 55](https://github.com/user-attachments/assets/8306567a-222a-4954-9661-2868bd6f6cc5)

虽然能用但是超载的话又会很卡，试过很多方法都不行，找了一圈都没看到有人提及或者解决，感觉这个无解了。

**Comment by CelestialSayuki** [comment]
如果你是我们机器，你的ID就应该用原来的。
其他ID读取的GFX AVG值是错的，Intel移动端都带锁怎么可能超载？
CPU频率低就是你自己pl1/2太低了，macOS的功率分配优先GPU，如果你感觉PL1还行，就测试体质，看看是不是大雷
与本EFI无关，故暂且关闭，可继续讨论
