### ISSUE TITLE
For overlocking XiaoXinAir14 超频的小新Air14无法在mac下超频

### ISSUE THREAD

**Issue by CelestialSayuki** [lietxia/XiaoXinAir14IML_2019_hackintosh#5]
I have overlocked my Xiaoxin, but contributor`s SSDT doesn`t support higher frequency

**Comment by CelestialSayuki** [comment]
It doesnt support 4400MHz and higher, please add 4400 4500 4600 4800 4900 5100. Thanks!
它不支持4400兆赫兹以上的频率，请添加4400 4500 4600 4800 4900 5100。谢谢！

**Comment by CelestialSayuki** [comment]
Mine is i7-10510U(1.8GHz)

**Comment by lietxia** [comment]
你可以试试这个，我没有i7-10510U的机器。I don't have i7-10510U model.You can try this

[i7-10510U-opencore_EFI.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4598595/i7-10510U-opencore_EFI.zip)
[i7-10510U-clover_EFI.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/4598646/i7-10510U-clover_EFI.zip)

**Comment by CelestialSayuki** [comment]
谢谢，这个可以支持更高频率。Thanks! This EFI supports higher frequency.

**Comment by CelestialSayuki** [comment]
5.0GHz大关已突破，烫麻了，请勿尝试！！！！！
